{% set version = '0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-etrunct
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/etrunct_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/etrunct/etrunct_{{ version }}.tar.gz
  sha256: 19b36c739e382be2f19bdbe4107337935d52a1ab8eb301326612318afdfbca2b

build:
  merge_build_host: True  # [win]
  number: 1003
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('etrunct')"           # [not win]
    - "\"%R%\" -e \"library('etrunct')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=etrunct
  license: MIT
  summary: Computes moments of univariate truncated t distribution. There is only one exported
    function, e_trunct(), which should be seen for details.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: etrunct
# Type: Package
# Title: Computes Moments of Univariate Truncated t Distribution
# Version: 0.1
# Author: Matthew Stephens
# Maintainer: Matthew Stephens <mstephens@uchicago.edu>
# Description: Computes moments of univariate truncated t distribution. There is only one exported function, e_trunct(), which should be seen for details.
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 5.0.1
# Suggests: testthat
# NeedsCompilation: no
# Packaged: 2016-07-03 15:43:09 UTC; stephens
# Repository: CRAN
# Date/Publication: 2016-07-04 09:12:55
