appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Mc6TeW2BtzJ9o6QXuAAfEX5ffsW5nQ5EaPoF5F1pPr+dNhUQkRHUusIgLJCEqii+HuRyGGl+Kuuk76EqmVTF7CxOGDlTsF0mLbZT/jgCRSaHLknH3E4wwbW7fCZHQOXHrn9aoV87cc2D1PzxWNQdrT1fF/XYjrivJpuIPePPMAlhIe25SUU1jfrxoPqOkv4xaJEsGh79hnT7Jr8VnuH1wOr4HdCjPUtsEpfaUfk5pWroeWG6EZWMdreSG1Z+ndtdNGakeDcUJ9fwgMsxFZvrBxwBBnfCTUsqJhh+aEQTto2LqKNfVlxmALm7GhI0a7MLetEDRBp0Ze7tV044/EJXa1tdj60nDfG06cYxnmK3DV2iMa494+rEFsLi08A+ZxrFFVI9rfMr6sgPcygIXxcXP002aeyBLa+RMs4ODvcbzt4WPJOYB+iFId36P1RaVXmjnkLZG7f1QetLbYn7BK1r2tHeUVd0ETBHg0Cp2DqemFa6nUjhjovxdn/SgYuHYx1dXIJbpRQ0nBfj82pFJS92s3Dn/5vJ6vZ+atDMqBQ/NHBXlDiaXr/4sjP6BoC1gaHL6vi+xzEvbGZ+11oWCg+JZqlwEl8YicwS1rmRe72jT/s4H4HGn35U+nf3N+8E1aJa/aJRbFBjA8reyxKDhZDcNXXo0VjNt4A+pg7OBgU405o=}
