travis:
  secure:
    BINSTAR_TOKEN: WATzqNjqHdZC09xTcydFXgXRlumOJrKur9YOZNaiL4ysu7BgfPfVysbqAy82adrBapyLyX2aGku0/GcerJag+zbRD07T0hnDLWZoxvwXEEBPPALcoiFcuWOhMP/UIxozb5HeLtBIexoPB13/3RcpBGTiCsPcGl2rMetakhQGjKPYiuC31fQryVBrueLll7bb9aBp4S3h7Xqiza65B1miXXbJT1Louqw3aA3GU93WlxeN+dn62YjOp41Cg/6u4sRHHj/gW/qYFKmul/xuEBmCCTvyXkSfqAqOOqO2jE1wHu6A6NAr0I+qwn153OyoDGi50RHP7WHFD3YnOj9HjvIEAZ1T8UA+JNmPvQVBQud1oQk1SnlnyVBfUbcuNr9DMt5g7BG5fS4q3Sn3eR/tSeH4l7R7W1p+q/Yxj7AWU9NpA5SQtbwRFJoDkydq7qMWLH9eRass0RAb63xkwHHS1nGKk9iJiaPI9rsNEjrTkFgZ4E6H3Iq4ZCbzWERR8euVWIGrlO7oIJKh+MQ89BRvGh14UiqvdItlvf/V0FEA5K+xH8Jr6vRTcEQvAWls1ZUDgeanXoUOVcT4r9ExqwbDWSABwYmNz2WBzm1PcbHjKQOdbFrpdBGc2F1W4hUkuV6hmEEq48PLqjcjcXrJKSl2DXF9UG1zWdC52iWUOTop0BaEm6c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
