travis:
  secure:
    BINSTAR_TOKEN: bZHShkc6PVSZZGZa+4dKLT53PWJqybysO5jhuX2vqZmN4NYAjQVSYwKWInK/Zaf+x6fE/WCROdsr7kS+XtWf1Fz9y06zR7+c7DElJmmdimVatLcEzhi6ZdBBbMJqVeI2xgZpcqm5l93JQBTKvuBtej9aXZoEXRHp/GkugYc4AELfDWBz1AWo6C3n3LLbF7vY8hXhT0PGNKEdx+hGEyfRU7IBszeIn+vhj2mzVfK677s+pkfPl7pLwSn6BNnsX/zWs0E9RL6knfVX3WdoIQJ0/cI2ei2g0UmovglDXoEcSdsosP/FRtUsjHl9jFSJ3n0su2tjCYumb22gTeii3YUT/nCiR6QdD8Qxk1h1WjslacuC23Je+bE8qM/wiiPafJHMr5/QL7Pq3L5ekzHd002sqTG8pQL6iKDsWGJLvhy9of0rotZas39Bga0RCfiWTx8CSpfDrWH0DuVwarKnWSqdF4IHRxmSF0wKxxxJVxkWA83y1iK/kpylZYmzmOMn7XinFJEmHHUu4rPvmq5xyyTZFZC2p2hDjsKCHkLLm6acCEOdLVKtwq4vHdrvXQPEPvMfj6Vm3NKTD47u3ID3/+S/l2SmXpj3tRPZMwcZQ62vWNPQPIMCjGPO+Zed9PCnyhEwnGsGbKyTl2gXcJZ0hxsYc42BdHmLk4FjmumV1+g28FE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
